// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WillieSandoval_2_28_2021.Data;

namespace WillieSandoval_2_28_2021.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210321021319_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WillieSandoval_2_28_2021.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(3000)")
                        .HasMaxLength(3000);

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("PayEnd")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PayStart")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("PayType")
                        .HasColumnType("int");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            DateEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Personal Project",
                            JobTitle = "N/A",
                            Location = "N/A",
                            Name = "Personal Project",
                            PayEnd = 0m,
                            PayStart = 0m,
                            PayType = 0
                        },
                        new
                        {
                            CompanyId = 2,
                            DateEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Paid work I completed for others",
                            JobTitle = "N/A",
                            Location = "N/A",
                            Name = "Paid Work",
                            PayEnd = 0m,
                            PayStart = 0m,
                            PayType = 0
                        },
                        new
                        {
                            CompanyId = 3,
                            DateEnd = new DateTime(2007, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2006, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Created test plans, manually tested, reported bugs, and created detailed documentation with supervision.",
                            JobTitle = "Intern - QA",
                            Location = "Austin, TX",
                            Name = "Austin Logistics",
                            PayEnd = 12m,
                            PayStart = 10m,
                            PayType = 0
                        },
                        new
                        {
                            CompanyId = 4,
                            DateEnd = new DateTime(2008, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2007, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Created and ran unit tests, created test plans, manually tested, reported bugs, and created detailed documentation with supervision.",
                            JobTitle = "Intern - QA",
                            Location = "Austin, TX",
                            Name = "Powered",
                            PayEnd = 17m,
                            PayStart = 15m,
                            PayType = 0
                        },
                        new
                        {
                            CompanyId = 5,
                            DateEnd = new DateTime(2009, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2009, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Created software for data validation using regular expressions with supervision.",
                            JobTitle = "Contract - Software Developer",
                            Location = "Plano, TX",
                            Name = "Optimal Blue",
                            PayEnd = 25m,
                            PayStart = 25m,
                            PayType = 0
                        },
                        new
                        {
                            CompanyId = 6,
                            DateEnd = new DateTime(2011, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2010, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Created algorithms to predict and analyze stock market behaviour with no supervision.",
                            JobTitle = "Contract - Software Developer",
                            Location = "Remotely",
                            Name = "Hedge Hog Capital",
                            PayEnd = 20m,
                            PayStart = 10m,
                            PayType = 0
                        },
                        new
                        {
                            CompanyId = 7,
                            DateEnd = new DateTime(2011, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2011, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Made improvements to front and backend to existing website with supervision.",
                            JobTitle = "Intern - Web Developer",
                            Location = "Fort Worth, TX",
                            Name = "iProspect (Range Online Media)",
                            PayEnd = 12m,
                            PayStart = 10m,
                            PayType = 0
                        },
                        new
                        {
                            CompanyId = 8,
                            DateEnd = new DateTime(2012, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2011, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Created reports, analyzed data for errors, and created a website with no supervision.",
                            JobTitle = "Software Developer",
                            Location = "Dallas, TX",
                            Name = "NexPay Inc (Talon)",
                            PayEnd = 45000m,
                            PayStart = 40000m,
                            PayType = 1
                        },
                        new
                        {
                            CompanyId = 9,
                            DateEnd = new DateTime(2018, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2012, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Managed and created new functionality to 3 websites on front and back end and tutored entry level programmer in a daily Agile environment.",
                            JobTitle = "Software Developer",
                            Location = "Remotely",
                            Name = "MRN3",
                            PayEnd = 65000m,
                            PayStart = 55000m,
                            PayType = 1
                        },
                        new
                        {
                            CompanyId = 10,
                            DateEnd = new DateTime(2020, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2018, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Added new features and removed bugs from front and backend to existing websites and software, created a new .NET MVC website, updated and cleaned code (introduced Design Patterns, modularized code, and added abstraction), and tutored entry level programmer with little to no supervision using Agile, Waterfall, and Spiral methods.",
                            JobTitle = "Software Developer",
                            Location = "Arlington, TX",
                            Name = "PPDocs",
                            PayEnd = 115000m,
                            PayStart = 80000m,
                            PayType = 1
                        });
                });

            modelBuilder.Entity("WillieSandoval_2_28_2021.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(8000);

                    b.Property<int>("ProjectDifficulty")
                        .HasColumnType("int");

                    b.Property<int>("ProjectImportance")
                        .HasColumnType("int");

                    b.Property<int>("ProjectType")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            CompanyId = 1,
                            Date = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "WillieSandoval.com",
                            Details = @"  <ul>
                                    <li>Created this website to display my portfolio, list of projects and previous employers, and share my knowledge with others</li>
                                    <li>Gained knowledge of:
                                        <ul>
                                            <li>.NET CORE</li>
                                            <li>Dependency Injection</li>
                                            <li>SOLID Principal</li>
                                        </ul>
                                    <li>Applied design patterns and SOLID principal</li>
                                    <li>SAMPLE CODE: <a href=""../SampleCodeCSharp/RepositoryPatternWithGenericsInDotNETCore"">Repository Pattern With Generics In .NET Core</a></li>
                                    <li>SAMPLE CODE: <a href=""https://github.com/longhorngraduate/WillieSandoval"">WillieSandoval.com on GitHub</a></li>
                                </ul>",
                            ProjectDifficulty = 2,
                            ProjectImportance = 3,
                            ProjectType = 4
                        },
                        new
                        {
                            ProjectId = 2,
                            CompanyId = 2,
                            Date = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DFWAirConditioningExperts.com",
                            Details = @"  <ul>
                                    <li>Created this website for a friend for his new HVAC repair business</li>
                                    <li>Gained knowledge of:
                                        <ul>
                                            <li>.NET MVC</li>
                                            <li>CSS (Mobile First)</li>
                                            <li>SEO</li>
                                            <li>Google Ads</li>
                                            <li>Google Analytics</li>
                                            <li>Tidio (integrated chat)</li>
                                            <li>Flickity</li>
                                            <li>FlexSlider</li>
                                        </ul>
                                    <li>No models were required</li>
                                    <li>SAMPLE CODE: <a href=""https://github.com/longhorngraduate/DFWAirConditioningExperts"">DFWAirConditioningExperts.com on GitHub</a></li>
                                </ul>",
                            ProjectDifficulty = 1,
                            ProjectImportance = 1,
                            ProjectType = 3
                        },
                        new
                        {
                            ProjectId = 3,
                            CompanyId = 2,
                            Date = new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ParentAgent.com",
                            Details = @"  <ul>
                                    <li>Created this website for a friend for his new tutoring business</li>
                                    <li>Gained knowledge of:
                                        <ul>
                                            <li>.NET MVC</li>
                                            <li>CSS Template</li>
                                            <li>LINQ</li>
                                            <li>.NET Identity (FB Login, User Roles)</li>
                                        </ul>
                                    <li>Did not apply design patterns nor SOLID principal because limited programming time</li>
                                    <li>SAMPLE CODE: <a href=""https://github.com/longhorngraduate/ParentAgent"">ParentAgent.com on GitHub</a></li>
                                </ul>",
                            ProjectDifficulty = 2,
                            ProjectImportance = 1,
                            ProjectType = 3
                        },
                        new
                        {
                            ProjectId = 4,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Accounting website",
                            Details = @"  <ul>
                                    <li>Old Accounting system had timeouts and runtime errors, had to be repaird or replaced</li>
                                    <li>Two coworkers and I created a new .NET MVC website with new UI and models</li>
                                    <li>Transferred data between old and new tables using TSQL in order to begin using code first migrations</li>
                                    <li>SAMPLE CODE: <a href=""../SampleCodeFrontEnd/JQueryDatatables"">JQuery Datatables</a></li>
                                </ul>",
                            ProjectDifficulty = 3,
                            ProjectImportance = 3,
                            ProjectType = 3
                        },
                        new
                        {
                            ProjectId = 5,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hybrid Closing (new revenue stream)",
                            Details = @"  <ul>
                                    <li>New project that read client's data from PDF files instead of webservices or webforms</li>
                                    <li>Used 3rd party OCR library and regular expressions to find specific pages, gather data from pages, and find the customers' signature lines</li>
                                    <li>Worked with Lead Programmer to design tables, backend (Webform and Winform), and UI</li>
                                    <li>Worked with Lead Programmer to create code to existing internal .NET Winform software to enable internal Doc Preparation team to run audits of the new retrieved data</li>
                                    <li>created new Webform UI</li>
                                    <li>edited existing Webform UI and business objects to work with the new logic (code to understand this was a new type of product and send PDF to DocuSign instead of custom Word/PDF files)</li>
                                    <li>added a tutorial using 3rd party JS Library that moved the user through sections of the project, highlighted active divs, and showed explanations</li>
                                    <li>Table based</li>
                                    <li>Did not apply design patterns nor SOLID principal because limited programming time and we took the mock-up/proof-of-concept and transformed it into final product.</li>
                                    <li>SAMPLE CODE: <a href=""../SampleCodeVBDotNET/GetSignatureCoordinatesFromPDF"">Get Signature Coordinates From PDF</a></li>
                                </ul>",
                            ProjectDifficulty = 3,
                            ProjectImportance = 3,
                            ProjectType = 7
                        },
                        new
                        {
                            ProjectId = 6,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Separate PDF Into Smaller PDFs (software for internal Doc Preparation team)",
                            Details = @"  <ul>
                                    <li>New internal software used to faciliate day-to-day operations when running audits for clients and their investors</li>
                                    <li>Used 3rd party OCR library, regular expressions, and advanced logic to separate PDF files into new smaller PDF files</li>
                                    <li>Read Data from PDF files</li>
                                    <li>Waterfall method</li>
                                    <li>Worked with and gathered project requirements from Doc Prep Lead</li>
                                    <li>Ran Extensive Tests to verify all docs were being captured</li>
                                    <li>Wrote both technical and non-technical documentation</li>
                                    <li>Did not apply design patterns nor SOLID principal because limited programming time and we took the mock-up/proof-of-concept and transformed it into final product.</li>
                                    <li>SAMPLE CODE: <a href=""../SampleCodeVBDotNET/SeparatePDFIntoSmallerPDFs"">Get Signature Coordinates From PDF</a></li>
                                </ul>",
                            ProjectDifficulty = 3,
                            ProjectImportance = 2,
                            ProjectType = 6
                        },
                        new
                        {
                            ProjectId = 7,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "System wide to use JQuery Datatable",
                            Details = @"  <ul>
                                    <li>JQuery Datatables gives the ability to easily create UI tables and uses built in pagination, sorting, filtering, and export capabilities in Excel, PDF, and others</li>
                                    <li>From programmer's POV, provides deferred loading with AJAX (web service), ability to use both HTTP Post and Get, reading data from JSON object that gets populated by and converted automatically from business object, strong library for client-side manipulation of the UI table when sorting and filtering, custom server-side pagination, and built in export</li>
                                    <li>SAMPLE CODE: <a href=""../SampleCodeFrontEnd/JQueryDatatablesCustom"">JQuery Datatables - added to existing code</a></li>
                                </ul>",
                            ProjectDifficulty = 3,
                            ProjectImportance = 3,
                            ProjectType = 7
                        },
                        new
                        {
                            ProjectId = 8,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ability for non-borrowers to view and receive updates on the loan's DocuSign documents",
                            Details = @"  <ul>
                                    <li>Gave ability to the client (non-borrower) to see their customers' DocuSign documents and signatures by also sending the client's data to DocuSign via web service</li>
                                    <li>Created more clarity between client and borrowers</li>
                                    <li>Reduced the time the Support and Doc Preparation teams had to spend diagnosing the problem and clarifying any confusion</li>
                                    <li>Thinking outside the box to suggest new solutions to problems no one had thought about</li>
                                    <li>Waterfall method</li>
                                    <li>SAMPLE CODE: <a href=""../SampleCodeVBDotNET/NonBorrowerToViewDocuSignDisclosureUpdates"">non-Borrower To View DocuSign Disclosure Updates</a></li>
                                </ul>",
                            ProjectDifficulty = 2,
                            ProjectImportance = 3,
                            ProjectType = 7
                        },
                        new
                        {
                            ProjectId = 9,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Runtime Error Notifications (Exception Handler)",
                            Details = "<ul><li>Created active monitoring of websites by emailing and logging new runtime errors</li><li>Edited web.config and other config file</li><li>Created new UI</li></ul>",
                            ProjectDifficulty = 2,
                            ProjectImportance = 3,
                            ProjectType = 7
                        },
                        new
                        {
                            ProjectId = 10,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Improved Security",
                            Details = "<ul><li>Edited web.config to make websites more secure</li></ul>",
                            ProjectDifficulty = 2,
                            ProjectImportance = 3,
                            ProjectType = 7
                        },
                        new
                        {
                            ProjectId = 11,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Package object's C# Sort to be used when Collapsing on the UI",
                            Details = @"  <ul>
                                    <li>TASK:
                                        <ul>
                                            <li>Created custom C# sort to rearrange Package objects, by datetime and then by their description</li>
                                            <li>Ability to collapse similar Packages on UI into 1 table row (edited UI to only display most recent and hide the visibility of the others until the maximize/minimize (+/-) feature were used on that table row)</li>
                                        </ul>
                                    </li>
                                    <li>PROBLEM:  I wasn't able to use LINQ twice because it wouldn't return the desired behavior; after sorting by datetime with LINQ, I needed to sort by the objects' description, so running the 2nd sort would unorganize them and wouldn't be sorted by datetime anymore.</li>
                                    <li>SOLUTION:  My approach was to run the datetime sort first using LINQ and then move any Package with the same description right behind the 1st occurence of that Package description. I wasn't able to use advanced sorting algorithms because of the situation I was in where I needed to keep the current datetime sort order.</li>
                                    <li>LEARNED/APPLIED KNOWLEDGE:  
                                        <ul>
                                            <li>Custom Sorting - Complex Algorithm</li>
                                            <li>Web Services with AJAX and AJAXPro</li>
                                            <li>Complex JS/JQuery to dynamically manipulate the DOM</li>
                                        </ul>
                                    </li>
                                    <li>SAMPLE CODE: <a href=""../SampleCodeVBDotNET/CustomSort"">Package Object's C# Sort</a></li>
                                </ul>",
                            ProjectDifficulty = 2,
                            ProjectImportance = 2,
                            ProjectType = 7
                        },
                        new
                        {
                            ProjectId = 12,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Supervised Programmer",
                            Details = "<ul><li>Tutored, mentored, and delegated tasks to mid-level programmer</li></ul>",
                            ProjectDifficulty = 2,
                            ProjectImportance = 3,
                            ProjectType = 9
                        },
                        new
                        {
                            ProjectId = 13,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chrome 80 Release Repairs",
                            Details = @"  <ul>
                                    <li>TASK:  Many clients reported not being able to save their data</li>
                                    <li>PROBLEM:  With the release of a new Chrome version that disabled onunload, onbeforeunload, and synchronous calls from running when the user left a webpage, many company's websites worldwide had issues. Chrome made this change to prevent websites from delaying or preventing user from leaving a webpage or closing a tab/window.</li>
                                    <li>SOLUTION:
                                        <ul>
                                            <li>I diagnosed the error by isolating the bug to Chrome, stepping through JS and pin pointing the issue, then investigating on Google and found the Chrome 80 release notes.</li>
                                            <li>Replaced all synchronous calls with asynchronous calls</li>
                                            <li>We were up and running later that day</li>
                                        </ul>
                                    </li>
                                    <li>SAMPLE CODE: <a href=""../SampleCodeFrontEnd/ChangeExitToAsyncCall"">Change Existing Exit Code to use Async calls</a></li>
                                </ul>",
                            ProjectDifficulty = 2,
                            ProjectImportance = 3,
                            ProjectType = 1
                        },
                        new
                        {
                            ProjectId = 14,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Remove \"Error Linking\" Runtime Errors",
                            Details = "<ul><li>One of our website's UI had an error that would appear randomly. Prevented users from saving.</li><li>Found the issue on the backend and fixed. Had to learn the business logic and steps clients took in order to pin point the issue.</li></ul>",
                            ProjectDifficulty = 3,
                            ProjectImportance = 3,
                            ProjectType = 1
                        },
                        new
                        {
                            ProjectId = 15,
                            CompanyId = 10,
                            Date = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prevent multiple disclosures from being sent",
                            Details = @"  <ul>
                                    <li>Logic Error:
                                        <ul>
                                            <li>Data was being sent to DocuSign via web service multiple times when it encountered errors</li>
                                            <li>caused confusion when the client's customers were to begin the eSign process and people were tracking these multiple documents created</li>
                                            <li>If the incorrect package(s) was eSigned, then the process had to be restarted, preventing loans from closing on the predicted date.</li>
                                        </ul>
                                    </li>
                                    <li>TASK:
                                        <ul>
                                            <li>Prevent multiple table entries from being created</li>
                                            <li>Only create entries into table after received response from DocuSign</li>
                                            <li>Notify user of error</li>
                                        </ul>
                                    </li>
                                </ul>",
                            ProjectDifficulty = 2,
                            ProjectImportance = 3,
                            ProjectType = 1
                        },
                        new
                        {
                            ProjectId = 16,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prevent incorrect Hybrid eSign package from appearing",
                            Details = "<ul><li>The website the client used to upload data and create new Hybrid loans, which were loans that accepted both wet and eSign signatures, had the ability to create multiple envelope entries into our DB per loan. Each envelope contained multiple wet and eSign packages. I then noticed the software that was used internally for data validation only created and updated the initial envelope's package.</li><li>After research, I communicated this logic error to the group where we decided to remove the ability to create multiple envelopes per loan. Although a good feature because it gave the client the ability to create multiple envelopes for testing or audit/history purposes, we were not in the position to work on this project.</li></ul>",
                            ProjectDifficulty = 1,
                            ProjectImportance = 3,
                            ProjectType = 1
                        },
                        new
                        {
                            ProjectId = 17,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Title company with ampersands displayed incorrectly",
                            Details = "<ul><li>The title company's fee descriptions with \"&\" displayed incorrectly, which prevented the loan from being compliant with government regulations.</li><li>After debugging, I discovered the ampersand was causing issues but couldn't update the data on data submission because it wasn't/couldn't be decoded on other parts of the website; instead, I found the class that was used to display on this particular section and added the escape characters.</li></ul>",
                            ProjectDifficulty = 2,
                            ProjectImportance = 3,
                            ProjectType = 1
                        },
                        new
                        {
                            ProjectId = 18,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Notify user that Template already locked",
                            Details = "<ul><li>When user is trying to gain access to the Templage Edit page, notify them that it is already locked/open by a different user</li><li>As a fail-safe, also prevent all the users already in the Template page from deleting or renaming locked templates.</li></ul>",
                            ProjectDifficulty = 1,
                            ProjectImportance = 2,
                            ProjectType = 7
                        },
                        new
                        {
                            ProjectId = 19,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add New Loans/Orders/Products",
                            Details = "<ul><li>Use knowledge of DB and backend to add new entries so clients can create new type of loans/orders/products</li></ul>",
                            ProjectDifficulty = 2,
                            ProjectImportance = 2,
                            ProjectType = 7
                        },
                        new
                        {
                            ProjectId = 20,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Limit certain users and client branches to access certain loans/orders/products",
                            Details = "<ul><li>Use knowledge of DB and backend to limit access</li><li>Flags and user groups were used</li></ul>",
                            ProjectDifficulty = 3,
                            ProjectImportance = 3,
                            ProjectType = 7
                        },
                        new
                        {
                            ProjectId = 21,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reports - Prevent Timeouts",
                            Details = "<ul><li>Reports, especially ones with historical data, were timing out.</li><li>Applied 1 or more of these:<ul><li>SQL query - optimized</li><li>SQL query - added pagination</li><li>C# - only returned requested rows</li><li>C# - update web services</li><li>C# - edit attributes to increase time limit</li><li>JQuery Datatables - built in and custom pagination</li></ul></li></ul>",
                            ProjectDifficulty = 2,
                            ProjectImportance = 2,
                            ProjectType = 1
                        },
                        new
                        {
                            ProjectId = 22,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reports - Create and Edit",
                            Details = "<ul><li>Applied 1 or more of these when creating new reports and updating existing ones:<ul><li>SQL query - optimized</li><li>SQL query - added pagination</li><li>C# - only returned requested rows</li><li>C# - update web services</li><li>JQuery Datatables - built in and custom pagination</li></ul></li></ul>",
                            ProjectDifficulty = 2,
                            ProjectImportance = 2,
                            ProjectType = 7
                        },
                        new
                        {
                            ProjectId = 23,
                            CompanyId = 10,
                            Date = new DateTime(2018, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nutshell's (CRM) Client data import (for Sales)",
                            Details = @"  <ul>
                                    <li>PROBLEM:  Our sales group needed a way to track leads, onboarding, and commision.</li>
                                    <li>SOLUTION:  I created new VB.NET code to utilize Nutshell's web services to send them client data when clients registered on our webpage.</li>
                                    <li>SAMPLE CODE: <a href=""../SampleCodeVBDotNET/NutshellWebServices"">Nutshell - Web Services</a></li>
                                </ul>",
                            ProjectDifficulty = 2,
                            ProjectImportance = 3,
                            ProjectType = 8
                        },
                        new
                        {
                            ProjectId = 24,
                            CompanyId = 10,
                            Date = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sales/Leads Reports and Form (for Sales)",
                            Details = "<ul><li>Our sales group needed an EASY way to track leads, onboarding, and commision.</li><li>I suggested we create our own CRM system instead of using Nutshell.com. A very simple customized system was needed in order to guarantee the Sales group would not stop using it down the road and was easy to learn.</li><li>Gathered requirements and desires from the Sales group and business owner.</li><li>As new interested parties registered for a demo, new entries were entered into the new Sales/Leads tables.</li><li>Introduced JQuery Datatables for the first time into our projects, added form submissions per row in order to update individual records.</li></ul>",
                            ProjectDifficulty = 2,
                            ProjectImportance = 3,
                            ProjectType = 8
                        },
                        new
                        {
                            ProjectId = 25,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Client Search (for Sales)",
                            Details = "<ul><li>Our sales group needed a report to display all the necessary data for a client, their branches, and users, and easily search on it.  Also, they wanted a feature where they could enter an address and see any client within a certain mile radius.</li><li>I gathered project requirements and created a report with many search field that used a fuzzy search.</li><li>I added and used Google's Map API, along with a table specifying distances between zipcodes, to calculate and display all clients on a map within a certain mile radius from an address or zip code entered.</li></ul>",
                            ProjectDifficulty = 3,
                            ProjectImportance = 2,
                            ProjectType = 8
                        },
                        new
                        {
                            ProjectId = 26,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Calculator/Help Feature (Flood Calculator)",
                            Details = "<ul><li>Our clients needed a way to see if their new and existing loans passed government regulations in order to receive Flood insurance and how much they could be insured for.</li><li>I created a new webpage with a dynamic form that used VB.NET and Windows controls to display new input elements and determine what the next scenario/state would be as the client entered data.</li><li>The solution was table-based where each record had a next and prev state. This table-based approach simplified coding on the businesslogic tier.</li></ul>",
                            ProjectDifficulty = 3,
                            ProjectImportance = 3,
                            ProjectType = 7
                        },
                        new
                        {
                            ProjectId = 27,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Loan Compare for Sales and Fulfillment team",
                            Details = "<ul><li>Created new webpage that compared a loan's previous and current data.</li></ul>",
                            ProjectDifficulty = 1,
                            ProjectImportance = 2,
                            ProjectType = 7
                        },
                        new
                        {
                            ProjectId = 28,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prevent user-error when entering emails with incorrect format - system wide",
                            Details = "<ul><li>Clients would copy and paste emails onto our forms from Excel files; the emails entered were formatted incorrectly at times.</li><li>For example, the string \"Willie Sandoval <willie@ppdocs.com>\" needed to be updated to \"willie@ppdocs.com\" on the client-side.</li><li>Created new JS function, made sure all pages included it, and applied to onblur.</li><li>Delegated portion of task to front end developer</li></ul>",
                            ProjectDifficulty = 1,
                            ProjectImportance = 1,
                            ProjectType = 7
                        },
                        new
                        {
                            ProjectId = 29,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add date calendar to date textboxes - system wide",
                            Details = "<ul><li>Found a good library to use.</li><li>Delegated task to front end developer</li></ul>",
                            ProjectDifficulty = 1,
                            ProjectImportance = 1,
                            ProjectType = 7
                        },
                        new
                        {
                            ProjectId = 30,
                            CompanyId = 10,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add an \"owner\" to the new PDF changes when user made custom changes to the PDF & only allow \"owner\" or managers to remove custom document",
                            Details = "<ul><li>When the system-created PDFs had client-requested custom changes or incorrect format due to large data fields, the client and our Doc Prep team had the ability to edit the PDFs. We needed a way to prevent these custom changes made to these PDFs from being removed by a different user or by our automated system when a loan was resubmitted for approval.</li><li>Our IT team discussed and we decided to only give managers and the person who edited the PDF the ability to edit or delete. I create a new field in the doc/PDF table that specified the person who made the change and then added new code to this section to only allow them or managers to edit or remove. Also, I had to trace the system to find the code that triggered when resubmitting loans and edited it.</li></ul>",
                            ProjectDifficulty = 3,
                            ProjectImportance = 3,
                            ProjectType = 1
                        },
                        new
                        {
                            ProjectId = 31,
                            CompanyId = 9,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "FAQ page for clients with default and client-specific Topics and Articles",
                            Details = @"
                        <ul>
                            <li>We needed an FAQ page for clients in order to display both default and client-specific topics and articles.</li>
                            <li>Requirements & Notes:
                                <ul>
                                    <li>Both topics and articles could become client-specific.</li>
                                    <li>If a default topic or article was edited for a client, it would only display the new version to the client.</li>
                                    <li>The client-specific topic and articles were tied back to the main default topic and article by referencing it in a field. If the field was null or 0, then that was the default topic or article.</li>
                                    <li>Vertical partioning was used to reduce the amount of data stored and returned.</li>
                                    <li>I was told by IT managers to move away from VBScript classes and use sps instead because it was prefered internally.</li>
                                    <li>...the list of requirements and design notes goes on and on....................</li>
                                </ul>
                            </li>
                            <li>SAMPLE CODE: <a href=""../SampleCodeSQL/AdvancedQuery"">Advanced Query</a></li>
                        </ul>",
                            ProjectDifficulty = 3,
                            ProjectImportance = 3,
                            ProjectType = 5
                        });
                });

            modelBuilder.Entity("WillieSandoval_2_28_2021.Models.ProjectsTopics", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("ProjectsTopics");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            TopicId = 1
                        },
                        new
                        {
                            ProjectId = 1,
                            TopicId = 6
                        },
                        new
                        {
                            ProjectId = 1,
                            TopicId = 10
                        },
                        new
                        {
                            ProjectId = 1,
                            TopicId = 20
                        },
                        new
                        {
                            ProjectId = 1,
                            TopicId = 21
                        },
                        new
                        {
                            ProjectId = 1,
                            TopicId = 22
                        },
                        new
                        {
                            ProjectId = 2,
                            TopicId = 3
                        },
                        new
                        {
                            ProjectId = 2,
                            TopicId = 8
                        },
                        new
                        {
                            ProjectId = 2,
                            TopicId = 10
                        },
                        new
                        {
                            ProjectId = 2,
                            TopicId = 23
                        },
                        new
                        {
                            ProjectId = 2,
                            TopicId = 24
                        });
                });

            modelBuilder.Entity("WillieSandoval_2_28_2021.Models.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = 1,
                            Name = "Agile"
                        },
                        new
                        {
                            TopicId = 2,
                            Name = "Waterfall"
                        },
                        new
                        {
                            TopicId = 3,
                            Name = "Spiral"
                        },
                        new
                        {
                            TopicId = 4,
                            Name = "TDD"
                        },
                        new
                        {
                            TopicId = 5,
                            Name = "Design Patterns"
                        },
                        new
                        {
                            TopicId = 6,
                            Name = ".NET MVC"
                        },
                        new
                        {
                            TopicId = 7,
                            Name = ".NET Core"
                        },
                        new
                        {
                            TopicId = 8,
                            Name = ".NET Webforms"
                        },
                        new
                        {
                            TopicId = 9,
                            Name = ".NET Winforms"
                        },
                        new
                        {
                            TopicId = 10,
                            Name = "C#"
                        },
                        new
                        {
                            TopicId = 11,
                            Name = "VB.NET"
                        },
                        new
                        {
                            TopicId = 12,
                            Name = "VBScript"
                        },
                        new
                        {
                            TopicId = 13,
                            Name = "SQL"
                        },
                        new
                        {
                            TopicId = 14,
                            Name = "TSQL"
                        },
                        new
                        {
                            TopicId = 15,
                            Name = "JS/JQuery"
                        },
                        new
                        {
                            TopicId = 16,
                            Name = "JQuery Datatables"
                        },
                        new
                        {
                            TopicId = 17,
                            Name = "CSS"
                        },
                        new
                        {
                            TopicId = 18,
                            Name = "CSS (mobile first)"
                        },
                        new
                        {
                            TopicId = 19,
                            Name = "XML"
                        },
                        new
                        {
                            TopicId = 20,
                            Name = "JSON"
                        },
                        new
                        {
                            TopicId = 21,
                            Name = "AJAX"
                        },
                        new
                        {
                            TopicId = 22,
                            Name = "Web Services"
                        },
                        new
                        {
                            TopicId = 23,
                            Name = "3rd Party Library"
                        },
                        new
                        {
                            TopicId = 24,
                            Name = "OCR"
                        },
                        new
                        {
                            TopicId = 25,
                            Name = "JS Libraries"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WillieSandoval_2_28_2021.Models.Project", b =>
                {
                    b.HasOne("WillieSandoval_2_28_2021.Models.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WillieSandoval_2_28_2021.Models.ProjectsTopics", b =>
                {
                    b.HasOne("WillieSandoval_2_28_2021.Models.Project", "Project")
                        .WithMany("ProjectsTopics")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WillieSandoval_2_28_2021.Models.Topic", "Topic")
                        .WithMany("ProjectsTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
